on:
  push:
    branches:
      - 'main'
name: deploy Production
env:
  REGISTRY: docker.pkg.github.com
  IMAGE_NAME: danny0327/cotizacion-web/cotizacion
jobs:
  build-and-push-intertransporte:
    name: build and push intertransporte
    runs-on: ubuntu-latest
    steps:
      -
        name: chekout
        uses: actions/checkout@v2
      -
        name: Login to github registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.NAME_GITHUB }}
          password: ${{ secrets.TOKEN }}
      -
        name: Build and push github registry
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}


